# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coin', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Duan',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True)),
                ('tinh', models.CharField(blank=True, max_length=200)),
                ('huyen', models.CharField(blank=True, max_length=200)),
                ('xa', models.CharField(blank=True, max_length=200)),
                ('details_address', models.TextField(null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pricefrom', models.FloatField(blank=True, null=True)),
                ('infoduan', models.TextField(blank=True, null=True)),
                ('tiendo', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('thumbs', models.TextField(blank=True, null=True)),
                ('uutien', models.IntegerField(default=0)),
                ('timecreate', models.DateTimeField()),
                ('timemodify', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupnode',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0)),
                ('type', models.BooleanField(default=1)),
                ('user', models.CharField(max_length=20)),
                ('staff', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Loaiduan',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.BooleanField(default=True)),
                ('typemod', models.IntegerField(default=0)),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Mod')),
            ],
        ),
        migrations.CreateModel(
            name='Phancong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=2000)),
                ('timemodify', models.DateTimeField()),
                ('modname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Mod')),
            ],
        ),
        migrations.CreateModel(
            name='Realestatenode',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('pricem2', models.FloatField(default=0)),
                ('area', models.FloatField(null=True)),
                ('tinh', models.CharField(max_length=200)),
                ('huyen', models.CharField(max_length=200)),
                ('xa', models.CharField(blank=True, max_length=200)),
                ('duong', models.CharField(blank=True, max_length=200)),
                ('details_address', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('huong', models.CharField(blank=True, max_length=200)),
                ('sophongngu', models.IntegerField(blank=True, null=True)),
                ('tang', models.IntegerField(blank=True, null=True)),
                ('sotang', models.IntegerField(blank=True, null=True)),
                ('rongtien', models.FloatField(default=0)),
                ('rongduong', models.FloatField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('thumbs', models.TextField(blank=True, null=True)),
                ('panorama_image', models.CharField(blank=True, max_length=2000, null=True)),
                ('tenduan', models.TextField(blank=True)),
                ('tenlienhe', models.CharField(max_length=200)),
                ('diachi', models.CharField(blank=True, max_length=2000)),
                ('dienthoai', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('timefrom', models.DateTimeField()),
                ('timeto', models.DateTimeField()),
                ('typenode', models.BooleanField(default=True)),
                ('vip', models.IntegerField(default=0)),
                ('modname', models.CharField(blank=True, max_length=200, null=True)),
                ('timecreate', models.DateTimeField()),
                ('timemodify', models.DateTimeField()),
                ('duanid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Duan')),
                ('modid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Mod')),
            ],
        ),
        migrations.CreateModel(
            name='Servicenode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('group', models.CharField(max_length=200)),
                ('modname', models.CharField(blank=True, max_length=200, null=True)),
                ('timecreate', models.DateTimeField()),
                ('timemodify', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duanid', models.CharField(max_length=20)),
                ('thumbs', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('timemodify', models.DateTimeField()),
                ('modname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Mod')),
            ],
        ),
        migrations.CreateModel(
            name='Typerealestate',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=1000)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typeservice',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.BooleanField(default=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('coin', models.CharField(max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='servicenode',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Typeservice'),
        ),
        migrations.AddField(
            model_name='realestatenode',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Typerealestate'),
        ),
        migrations.AddField(
            model_name='realestatenode',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.User'),
        ),
        migrations.AddField(
            model_name='duan',
            name='modname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Mod'),
        ),
        migrations.AddField(
            model_name='duan',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Loaiduan'),
        ),
        migrations.AddField(
            model_name='coin',
            name='typerealestate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Typerealestate'),
        ),
    ]
