# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_duanquantam'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanquantam',
            name='timemodify',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
