# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_duanquantam_timemodify'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='vip',
            field=models.IntegerField(default=0),
        ),
    ]
