# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_coin_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='typerealestate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Typerealestate'),
        ),
    ]
