# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180126_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duanquantam',
            name='details',
        ),
        migrations.RemoveField(
            model_name='duanquantam',
            name='timemodify',
        ),
    ]
