# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_history_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thongbao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Thongbaouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modname', models.TextField(blank=True, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('thongbao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Thongbao')),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='staff',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
