# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180201_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
    ]
