# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='profile/%Y/%m/%d'),
        ),
    ]
