# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20180205_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='no-img.jpg', upload_to='profile'),
        ),
    ]
