# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20180205_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='profile'),
        ),
    ]
