# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_auto_20180205_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatenode',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
