# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_realestatenode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='duan',
            name='anh360',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duan',
            name='panorama_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duan',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestatenode',
            name='anh360',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.TextField(blank=True),
        ),
    ]
