# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20180208_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
