# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20180313_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messagenode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Realestatenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='converid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Messagenode'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.User'),
        ),
    ]
