# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20180502_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.User'),
        ),
        migrations.AlterField(
            model_name='messagenode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.Realestatenode'),
        ),
        migrations.AlterField(
            model_name='messagenode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.User'),
        ),
    ]
