# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20180502_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to='companies.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to='companies.User'),
        ),
        migrations.AlterField(
            model_name='messagenode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='companies.Realestatenode'),
        ),
        migrations.AlterField(
            model_name='messagenode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagenode_user', to='companies.User'),
        ),
    ]
